language: go

go:
  - 1.11
  - 1.12

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v0.5.4/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

install:
  - make install

script: make test
