[[constraint]]
  name = "github.com/aws/aws-lambda-go"
  version = "1.6.0"

[[constraint]]
  name = "github.com/jkomyno/palitra"
  version = "1.0.0"

[prune]
  go-tests = true
  unused-packages = true
